name: Publish
on:
    release:
        types:
            - published
    workflow_dispatch: {}
jobs:
    build:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write # NPM provenance
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Yarn
              run: |
                  corepack prepare yarn@4.9.2 --activate
                  yarn set version 4.9.2

            - name: Use Node.js LTS
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  registry-url: "https://registry.npmjs.org"

            -   name: Install dependencies
                run: yarn install --immutable #--immutable-cache --check-cache

            - name: Build library
              run: yarn build
              env:
                  CI: true

            - name: Build example
              run: yarn build
              env:
                  CI: true

            # Publish Package
            - name: Publish all packages
              if: startsWith(github.ref, 'refs/tags/v')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  yarn run gh-pages
                  npm publish --provenance --access public
